# Generated by Django 4.0.4 on 2022-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'locations',
                'db_table': 'location',
                'ordering': ['id'],
            },
        ),
    ]
